cash/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', index, name="main"),
    path('exchange/', ExchangeCreateView.as_view()),
    path('test/', posterview)
	]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('cash.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cash/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class CurrencyRate(models.Model):
    name = models.CharField(max_length=100)
    buy_rate = models.DecimalField(max_digits=100, null=True, decimal_places=2)
    sell_rate = models.DecimalField(max_digits=100, null=True, decimal_places=2)
    created_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Case(models.Model):
    code = models.CharField(max_length=50)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Exchange(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    summa = models.DecimalField(max_digits=200, decimal_places=2)
    rate = models.ForeignKey(CurrencyRate, on_delete=models.DO_NOTHING)
    case = models.ForeignKey(Case, on_delete=models.DO_NOTHING)
    check = models.CharField(max_length=250, blank=True, null=True)
    total_sum = models.DecimalField(null=True, blank=True, max_digits=200, decimal_places=2)

    def __str__(self):
        return str(self.id)




def check_save(instance, sender, **kwargs):
    if kwargs['created']:
        case = instance.case
        rate = instance.rate
        if case.id == 1:
            instance.total_sum = instance.summa * rate.buy_rate
            instance.check = 'A - 0' + str(instance.id)
        elif case.id == 2:
            instance.total_sum = instance.summa * rate.sell_rate
            instance.check = 'B - 0' + str(instance.id)
        instance.save()


post_save.connect(receiver=check_save, sender=Exchange)

cash/forms.py
from django import forms
from .models import Exchange

class Myform(forms.ModelForm):
	class Meta:
		model = Exchange
		fields = '__all__'

cash/views.py
from django.shortcuts import render
from rest_framework.generics import ListCreateAPIView

from .serializers import ExchangeSerializer
from .models import Exchange
from .forms import *

def index(request):
    return render(request, 'apps/index.html', {})

class ExchangeCreateView(ListCreateAPIView):
    queryset = Exchange.objects.all()
    serializer_class = ExchangeSerializer

#    def perform_create(self, serializer):
#        serializer.save(user=self.request.user)

def posterview(request):
	template_name = 'test.html'
	myform =  Myform(request.POST or None)
	context = {
		'myform': myform
	}
	return render(request, template_name, context)

templates/apps/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'admin/css' %}"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}">
    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Hidden brand</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/bootstrap.js' %}"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css' %}"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="#">Hidden brand</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="{% static 'js/bootstrap.js' %}"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
	<title>testportjquery</title>
</head>
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<body>
<div class="container">
	<div class="content col-sm-12">
		<form>
			<div class="form-group">
			    <label for="{{ myform.summa.id_for_label }}">{{ myform.summa.html_name }}</label>
			    <input type="text" class="form-control" id="{{ myform.summa.id_for_label }}" placeholder="Enter summa">
			</div>
			<div class="form-group">
				<label for="{{ myform.rate.id_for_label }}">{{ myform.rate.html_name }}</label>
				<select class="form-control" id="{{ myform.rate.id_for_label }}">
					{% for i in myform.rate %}
						<option>{{ i }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group">
				<label for="{{ myform.case.id_for_label }}">{{ myform.case.html_name }}</label>
				<select class="form-control" id="{{ myform.case.id_for_label }}">
					{% for i in myform.case %}
						<option>{{ i }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group">
			    <label for="{{ myform.total_sum.id_for_label }}">{{ myform.total_sum.html_name }}</label>
			    <input type="text" class="form-control" id="{{ myform.total_sum.id_for_label }}" placeholder="Enter case">
			</div>
			<input id="username" value="{{ user.id }}" hidden>
			<button type="submit" id="submit" class="btn btn-primary">Submit</button>
		</form>
	</div>
</div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script type="text/javascript">
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie != '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        //var csrftoken = getCookie('csrftoken');

        $(function () {
            $.ajaxSetup({
                headers: {
                    "X-CSRFToken": getCookie("csrftoken")
                }
            });
        });
        $(function(){
            $("#submit").on('click', function(){
                data = {
                	'user': $('#username').val(),
                	'summa': $('#id_summa').val(),
                	'rate': $('#id_rate').val(),
                	'case': $('#id_case').val(),
                	'total_sum': $('#id_total_sum').val()

                };
                $.ajax({
                    url: '/exchange/',
                    method: 'POST',
                    datatype: 'JSON',
                    contentType: 'application/json',
                    data: JSON.stringify(data),
                    error: function(xhr, ajaxOptions, thrownError) {
                        console.log(data);
                        console.log(xhr);
                        console.log(thrownError);
                        alert(xhr.responseText);
                    },
                    success: function(){
                        alert("Успешно сохранено !");
                    }
                })
            })
        })
    </script>
</body>
</html>